"use client";

import { ArrowUpRight, Check, ChevronRight, CircleHelp, Cloud, Download, Link2, LockKeyhole, Plus, Search, SlidersHorizontal, Sparkles, TrendingUp } from "lucide-react";

import { pageMeta } from "@/lib/navigation";

const collections = {
  "/accounts": { statLabel: "Saldo consolidado", stat: "R$ 18.270,00", action: "Adicionar conta", items: [["Nubank", "Conta corrente", "R$ 2.450,00"], ["Banco do Brasil", "Conta corrente", "R$ 5.820,00"], ["Inter", "Conta digital", "R$ 9.999,00"]] },
  "/cards": { statLabel: "Limite disponível", stat: "R$ 8.240,50", action: "Adicionar cartão", items: [["Nubank Ultravioleta", "final 1234 · fatura atual", "R$ 1.240,50"], ["Itaú Click", "final 8821 · fatura atual", "R$ 518,20"]] },
  "/goals": { statLabel: "Progresso total", stat: "68%", action: "Nova meta", items: [["Reserva de emergência", "R$ 7.500 de R$ 10.000", "75%"], ["Viagem de fim de ano", "R$ 2.180 de R$ 6.000", "36%"], ["Curso de especialização", "R$ 1.200 de R$ 2.400", "50%"]] },
  "/investments": { statLabel: "Patrimônio investido", stat: "R$ 25.400,00", action: "Adicionar investimento", items: [["Renda fixa", "Tesouro e CDBs", "R$ 12.000"], ["Ações", "Carteira de longo prazo", "R$ 8.400"], ["FIIs", "Renda imobiliária", "R$ 3.000"]] },
} as const;

const transactionRows = [["09 set", "Salário mensal", "Receitas", "+ R$ 4.500,00"], ["09 set", "iFood", "Alimentação", "− R$ 45,90"], ["08 set", "Uber", "Transporte", "− R$ 21,40"], ["07 set", "Aluguel", "Moradia", "− R$ 1.850,00"], ["05 set", "Freelance", "Receitas", "+ R$ 980,00"]];

export function SectionView({ path }: { path: string }) {
  const meta = pageMeta[path];
  const collection = collections[path as keyof typeof collections];
  const isTransactions = path === "/transactions";
  const isOpenFinance = path === "/open-finance";
  const isAi = path === "/ai";
  const isReports = path === "/reports";
  const isSettings = path === "/settings";

  return <div className="space-y-7">
    <section className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow">{meta.eyebrow}</p><h2 className="mt-2 text-3xl font-bold tracking-[-0.04em]">{meta.title}</h2><p className="mt-2 max-w-xl text-sm text-slate-500">{meta.description}</p></div>{!isReports && !isSettings && <button className="button-primary"><Plus size={17} /> {collection?.action ?? "Adicionar item"}</button>}</section>

    {collection && <><section className="grid max-w-sm gap-4"><article className="surface-card p-5"><p className="text-xs font-medium text-slate-500">{collection.statLabel}</p><strong className="mt-2 block text-3xl tracking-tight">{collection.stat}</strong><div className="mt-4 flex items-center gap-2 text-xs text-emerald-700"><TrendingUp size={14} /> 8,4% neste ano</div></article></section><section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{collection.items.map(([name, detail, amount], index) => <article key={name} className="surface-card p-5"><div className={`grid size-10 place-items-center rounded-xl ${index === 0 ? "bg-lime-100 text-lime-800" : index === 1 ? "bg-sky-100 text-sky-800" : "bg-orange-100 text-orange-800"}`}><Sparkles size={17} /></div><h3 className="mt-7 font-bold">{name}</h3><p className="mt-1 text-xs text-slate-500">{detail}</p><strong className="mt-5 block text-xl">{amount}</strong>{path === "/goals" && <div className="mt-4 h-2 rounded-full bg-slate-100"><div className="h-full w-3/4 rounded-full bg-lime-300" /></div>}</article>)}</section></>}

    {isTransactions && <article className="surface-card overflow-hidden"><div className="flex flex-col gap-3 border-b border-slate-100 p-5 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={16} /><input className="field pl-10" placeholder="Buscar transações..." /></div><button className="select-button"><SlidersHorizontal size={15} /> Filtros</button></div><div className="hidden grid-cols-[100px_1fr_1fr_160px] gap-4 bg-slate-50 px-5 py-3 text-[10px] font-bold uppercase tracking-wider text-slate-500 sm:grid"><span>Data</span><span>Descrição</span><span>Categoria</span><span className="text-right">Valor</span></div><div className="divide-y divide-slate-100">{transactionRows.map(([date, title, category, amount]) => <div key={title} className="grid gap-2 px-5 py-4 sm:grid-cols-[100px_1fr_1fr_160px] sm:items-center sm:gap-4"><span className="text-xs text-slate-500">{date}</span><span className="font-semibold">{title}</span><span className="text-xs text-slate-500">{category}</span><strong className={`sm:text-right ${amount.startsWith("+") ? "text-emerald-700" : ""}`}>{amount}</strong></div>)}</div></article>}

    {isOpenFinance && <div className="grid gap-5 lg:grid-cols-[1fr_1.1fr]"><article className="surface-card border-dashed p-7 text-center sm:p-10"><span className="mx-auto grid size-12 place-items-center rounded-2xl bg-lime-100 text-lime-800"><Link2 size={22} /></span><h3 className="mt-5 text-xl font-bold">Conecte suas instituições</h3><p className="mx-auto mt-2 max-w-sm text-sm leading-6 text-slate-500">A conexão real será habilitada posteriormente conforme os requisitos do Open Finance Brasil.</p><button className="button-primary mx-auto mt-6"><Plus size={17} /> Conectar instituição</button><div className="mt-7 flex items-center justify-center gap-2 text-xs text-slate-500"><LockKeyhole size={14} /> Você mantém o controle dos seus dados</div></article><article className="surface-card p-6"><div className="flex items-center justify-between"><div><p className="eyebrow">Ambiente preparado</p><h3 className="mt-1 text-lg font-bold">Instituições conectadas</h3></div><Cloud className="text-slate-400" size={20} /></div>{["Nubank", "Banco do Brasil"].map((bank) => <div key={bank} className="mt-5 flex items-center gap-3 border-t border-slate-100 pt-4"><span className="grid size-10 place-items-center rounded-xl bg-slate-100 font-bold text-slate-700">{bank[0]}</span><span className="flex-1"><b className="block text-sm">{bank}</b><small className="text-xs text-slate-500">Nenhum dado sincronizado</small></span><span className="flex items-center gap-1 text-xs text-slate-400"><CircleHelp size={13} /> Em breve</span></div>)}</article></div>}

    {isAi && <article className="surface-card mx-auto max-w-3xl p-6 sm:p-10"><div className="grid size-12 place-items-center rounded-2xl bg-[#10252a] text-lime-300"><Sparkles size={22} /></div><h3 className="mt-7 text-2xl font-bold">Como posso ajudar?</h3><p className="mt-2 text-sm text-slate-500">Pergunte sobre suas finanças quando a camada de inteligência estiver conectada às ferramentas do backend.</p><div className="mt-7 grid gap-3 sm:grid-cols-3">{["Quanto gastei com alimentação?", "Posso economizar este mês?", "Como está minha saúde financeira?"].map((question) => <button key={question} className="rounded-xl border border-slate-200 p-3 text-left text-xs font-medium transition-colors hover:border-slate-950">{question}</button>)}</div><div className="mt-8 flex items-center gap-3 border-t border-slate-100 pt-5"><input className="field" placeholder="Pergunte sobre suas finanças..." disabled /><button className="button-primary shrink-0" disabled>Enviar</button></div></article>}

    {isReports && <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{["Gastos mensais", "Fluxo de caixa", "Evolução patrimonial", "Gastos por categoria", "Receitas", "Investimentos"].map((report) => <article key={report} className="surface-card group p-5 transition-transform hover:-translate-y-1"><div className="flex items-center justify-between"><span className="grid size-10 place-items-center rounded-xl bg-sky-100 text-sky-800"><ArrowUpRight size={18} /></span><Download size={16} className="text-slate-400" /></div><h3 className="mt-8 font-bold">{report}</h3><p className="mt-1 text-xs text-slate-500">Visualização demonstrativa</p></article>)}</div>}

    {isSettings && <div className="grid max-w-3xl gap-3">{["Perfil", "Segurança", "Notificações", "Privacidade", "Instituições conectadas", "Preferências", "Assinatura", "Excluir conta"].map((item, index) => <button key={item} className="surface-card flex items-center gap-4 p-4 text-left transition-colors hover:border-slate-400"><span className="grid size-9 place-items-center rounded-lg bg-slate-100 text-xs font-bold text-slate-600">{String(index + 1).padStart(2, "0")}</span><span className="flex-1 text-sm font-semibold">{item}</span><ChevronRight size={17} className="text-slate-400" /></button>)}</div>}

    {!collection && !isTransactions && !isOpenFinance && !isAi && !isReports && !isSettings && <article className="surface-card p-8"><div className="grid size-11 place-items-center rounded-xl bg-lime-100 text-lime-800"><Check size={20} /></div><h3 className="mt-6 text-xl font-bold">Espaço pronto para seus dados</h3><p className="mt-2 max-w-xl text-sm leading-6 text-slate-500">A estrutura visual desta área está pronta. A integração com o backend será adicionada quando o domínio correspondente estiver disponível.</p></article>}

    <div className="flex items-center gap-2 rounded-xl border border-slate-200 bg-white/50 px-4 py-3 text-xs text-slate-500"><CircleHelp size={15} /><span>Modo demonstração: nenhuma ação nesta tela altera dados reais.</span></div>
  </div>;
}
